// Maksym Chumak
// April 14, 2020
// Jenkins pipeline for sample_code2 project

pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                sh 'echo "Installing the Python Requirements..."'
                sh "pip install -r requirements.txt"
                sh 'echo "Requirement complete."'
            }
        }
        stage("Code Quality") {
            steps {
                sh "pylint-fail-under --fail_under 7.0 *.py"
            }
        }
        stage("Code Quantity") {
            steps {
                sh "find . -name '*.py' | wc -l"
            }
        }
    }
}
